import fsp from 'node:fs/promises';
import path from 'node:path';
import { parseFrontmatter } from '../packages/core/src/kb/frontmatter.ts';

const root = path.resolve(process.argv[2] ?? '');
const apply = process.argv.includes('--apply');
if (!root || root === path.parse(root).root)
  throw new Error('pass the knowledge-base root as the first argument');

const synthesize = [
  /^people\/[^/]+\.md$/,
  /^companies\/[^/]+\.md$/,
  /^wiki\/sightseeings\/.+\.md$/,
  /^travel\/(?!templates\/).+\.md$/,
];
const hygiene = [/^[^/]+\/(?:music-repertoire|game-list)\.md$/, /^[^/]+\/books\/reading-list\.md$/];

const pages = await markdownFiles(root);
const changed: string[] = [];
for (const relPath of pages) {
  const dream = hygiene.some((pattern) => pattern.test(relPath))
    ? 'hygiene'
    : synthesize.some((pattern) => pattern.test(relPath))
      ? 'synthesize'
      : null;
  if (!dream) continue;
  const absPath = path.join(root, relPath);
  const before = await fsp.readFile(absPath, 'utf8');
  const after = addDreamPolicy(before, dream);
  if (after === before) continue;
  changed.push(relPath);
  if (apply) await fsp.writeFile(absPath, after, 'utf8');
}

const configPath = path.join(root, 'akno.json');
const configBefore = await fsp.readFile(configPath, 'utf8');
const personSlugs = pages
  .map((relPath) => /^people\/([^/]+)\.md$/.exec(relPath)?.[1] ?? null)
  .filter((slug): slug is string => slug !== null);
const personalFolderSlugs = personSlugs.filter((slug) =>
  pages.some((relPath) => relPath.startsWith(`${slug}/`)),
);
const configAfter = migrateRules(configBefore, personSlugs, personalFolderSlugs);
if (configAfter !== configBefore) {
  changed.push('akno.json');
  if (apply) await fsp.writeFile(configPath, configAfter, 'utf8');
}

process.stdout.write(
  `${apply ? 'migrated' : 'would migrate'} ${changed.length} file(s)\n${changed.join('\n')}\n`,
);

function addDreamPolicy(content: string, dream: 'hygiene' | 'synthesize'): string {
  const fm = parseFrontmatter(content);
  if (!fm.present) {
    return `---\nakno:\n  management:\n    dream: ${dream}\n---\n\n${content}`;
  }
  const current = fm.data.akno;
  if (current && typeof current === 'object' && !Array.isArray(current)) {
    const management = (current as Record<string, unknown>).management;
    if (management && typeof management === 'object' && !Array.isArray(management)) {
      if ((management as Record<string, unknown>).dream === dream) return content;
      throw new Error('manual migration required: page already declares akno.management.dream');
    }
    throw new Error('manual migration required: page already has an akno block');
  }
  const head = content.slice(0, fm.bodyOffset);
  const close = head.lastIndexOf('---');
  if (close <= 0) throw new Error('could not locate closing frontmatter fence');
  return `${head.slice(0, close)}akno:\n  management:\n    dream: ${dream}\n${head.slice(close)}${content.slice(fm.bodyOffset)}`;
}

function migrateRules(source: string, profileSlugs: string[], activePersonalSlugs: string[]): string {
  let text = source
    .replace(
      '// Three classes (§5). `full` is the default and needs no entry here:',
      '// Page roles and automatic-management policy:',
    )
    .replace(
      '//   full       indexed, recall returns matching lines, mined for facts',
      '//   knowledge  canonical claims; eligible for fact derivation',
    )
    .replace(
      '//   reference  indexed and searchable, quoted in a capped window, never mined for facts',
      '//   source     searchable evidence; never mined for facts or changed automatically',
    )
    .replace('//   excluded   not indexed at all', '//   ignored    not indexed at all')
    .replace(
      '// The point of `reference` is not speed, it is truth: reference pages are evidence,',
      '// Role is about contribution, not authority: source pages are evidence,',
    )
    .replace(
      '// full pages are claims, and only claims become facts. A transcript saying "maybe we',
      '// knowledge pages are claims, and only claims become facts. A transcript saying "maybe we',
    );

  // First translate every existing role declaration, including knowledge-base-specific paths
  // this generic migration has never seen. Named overrides below then give canonical branches
  // their intended policy and descriptions.
  text = text
    .replace(/"class"\s*:\s*"reference"/g, '"role": "source", "remember": "deny"')
    .replace(/"class"\s*:\s*"excluded"/g, '"role": "ignored", "remember": "deny"')
    .replace(/"class"\s*:\s*"full"/g, '"role": "knowledge", "remember": "integrate"');

  // Do not declare a personal branch merely because a canonical profile exists. A rule for a
  // directory absent from disk would appear to `remember` as a destination and then fail its
  // physical-folder guard. Remove only lines generated by this migration, identified by their
  // exact generic description.
  for (const slug of profileSlugs.filter((entry) => !activePersonalSlugs.includes(entry))) {
    const key = JSON.stringify(`${slug}/**`).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const generated = new RegExp(
      `^\\s*${key}\\s*:\\s*\\{[^\\n]*"description":"Records, preferences, projects and personal knowledge for this person\\."[^\\n]*\\},?\\n?`,
      'm',
    );
    text = text.replace(generated, '');
  }

  const rules: Record<string, Record<string, unknown>> = {
    'conversations/**': {
      role: 'source',
      remember: 'deny',
      type: 'conversation',
      description: 'Chat transcripts and discussion history; searchable evidence, not canonical claims.',
    },
    'articles/**': { role: 'source', remember: 'deny', description: 'Saved articles and external prose.' },
    'research/**': {
      role: 'source',
      remember: 'deny',
      description:
        'Research material and external evidence; durable conclusions belong in wiki or another canonical page.',
    },
    'resources/**': {
      role: 'source',
      remember: 'deny',
      description: 'External resources and reference material.',
    },
    'learning/**': {
      role: 'knowledge',
      remember: 'integrate',
      description: 'Canonical notes about learned concepts and techniques.',
    },
    'wiki/**': {
      role: 'knowledge',
      remember: 'integrate',
      description: 'Canonical knowledge about games, places, media, products and other subjects.',
    },
    'people/**': { role: 'knowledge', remember: 'integrate', description: 'Canonical profiles for people.' },
    'companies/**': {
      role: 'knowledge',
      remember: 'integrate',
      description: 'Canonical profiles for companies and organizations.',
    },
    'travel/**': {
      role: 'knowledge',
      remember: 'integrate',
      description: 'Trips, itineraries, bookings and travel knowledge.',
    },
    'travel/templates/**': {
      role: 'ignored',
      remember: 'deny',
      description: 'Blank trip templates, not memory.',
    },
    llama_bench_report: { role: 'ignored', remember: 'deny', description: 'Generated benchmark output.' },
    'inbox/**': {
      role: 'ignored',
      remember: 'deny',
      ingest: 'auto',
      route: true,
      description: 'Temporary ingestion inbox; files leave after routing.',
    },
    'receipts/**': {
      role: 'source',
      remember: 'deny',
      ingest: 'auto',
      description: 'Scanned bills, receipts and statements used as evidence.',
    },
  };

  for (const slug of activePersonalSlugs) {
    rules[`${slug}/**`] = {
      role: 'knowledge',
      remember: 'integrate',
      about: [`people/${slug}`],
      description: 'Records, preferences, projects and personal knowledge for this person.',
    };
    const projectsGlob = `${slug}/projects/**`;
    if (source.includes(JSON.stringify(projectsGlob))) {
      rules[projectsGlob] = {
        role: 'knowledge',
        remember: 'integrate',
        about: [`people/${slug}`],
        description: 'Project specifications and notes owned by this person.',
      };
    }
  }

  for (const [glob, rule] of Object.entries(rules)) {
    const pattern = new RegExp(
      `^(\\s*)${JSON.stringify(glob).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:\\s*\\{[^\\n]*\\}(,?)`,
      'm',
    );
    const rendered = `${JSON.stringify(glob)}: ${JSON.stringify(rule)}`;
    if (pattern.test(text))
      text = text.replace(pattern, (_whole, indent: string, comma: string) => `${indent}${rendered}${comma}`);
    else {
      const close = text.lastIndexOf('\n  }');
      if (close < 0) throw new Error('akno.json has no folders block');
      const before = text.slice(0, close).replace(/\s+$/, '');
      const comma = /}\s*$/.test(before) ? ',' : '';
      text = `${before}${comma}\n    ${rendered}\n${text.slice(close)}`;
    }
  }
  return text;
}

async function markdownFiles(directory: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await fsp.readdir(directory, { withFileTypes: true, recursive: true });
  for (const entry of entries) {
    if (!entry.isFile() || !/\.md$/i.test(entry.name)) continue;
    const abs = path.join(entry.parentPath ?? directory, entry.name);
    out.push(path.relative(directory, abs).replace(/\\/g, '/'));
  }
  return out.sort();
}
