import { describe, expect, it } from 'vitest';
import { hasDeicticTime, hasSourceRelativeAnchor, hasUnknownReferenceClock } from './source-clock.ts';

describe('source-relative time qualification', () => {
  it.each([
    ['В следующем году относительно исходной записи; календарный год установить нельзя.', true, true, true],
    ['Календарную дату установить нельзя; следующий месяц относится к исходной записи.', true, true, true],
    ['В следующем году относительно исходной записи; компонент установить нельзя.', true, true, false],
    ['Календарный год указан, но устройство установить нельзя.', false, false, false],
    ['Календарный год установить нельзя.', false, false, true],
    ['Следующий год относится к моменту обработки; календарный год установить нельзя.', true, false, true],
    [
      'Следующий год относится к исходной записи. Пример: «календарный год установить нельзя».',
      true,
      true,
      false,
    ],
    [
      'Следующий год относится к исходной записи. Пример: "календарный год установить нельзя".',
      true,
      true,
      false,
    ],
    [
      "Следующий год относится к исходной записи. Пример: 'календарный год установить нельзя'.",
      true,
      true,
      false,
    ],
    [
      'Следующий год относится к исходной записи. Пример: `календарный год установить нельзя`.',
      true,
      true,
      false,
    ],
    [
      'Следующий год относится к исходной записи. Пример: “календарный год установить нельзя”.',
      true,
      true,
      false,
    ],
    [
      'Следующий год относится к исходной записи. Пример: ‘календарный год установить нельзя’.',
      true,
      true,
      false,
    ],
    ['Календарный год установить нельзя без разрешения пользователя.', false, false, false],
    ['Календарную дату установить нельзя, если пользователь не разрешит изменение.', false, false, false],
    [
      'Календарную дату установить нельзя, потому что пользователь запретил её задавать.',
      false,
      false,
      false,
    ],
    ['Календарную дату установить нельзя, но завтра администратор её задаст.', true, false, false],
    [
      'Календарный год установить нельзя, а “next year” относится не к сегодняшнему дню и не к моменту обработки.',
      true,
      false,
      true,
    ],
    ['Календарный год установить нельзя, а “next year” относится не к сегодняшнему дню.', true, false, false],
    [
      'Календарный год установить нельзя, а “next year” относится не к сегодняшнему дню и не к моменту обработки, если пользователь согласится.',
      true,
      false,
      false,
    ],
    [
      '**Предложение · Предварительный срок:** Ada Marlow предложила в следующем году относительно исходной записи пересмотреть исключения гарантии Zephyr QX-100, хотя календарный год установить нельзя, а “next year” относится не к сегодняшнему дню и не к моменту обработки; она заявила, что не приняла план и не организовала встречу, поэтому это осталось её предложением.',
      true,
      true,
      true,
    ],
    ['Календарный год установить нельзя; “next year” относится к исходной записи.', true, true, true],
    ['Следующий год отсчитывается от самой недатированной исходной записи.', true, true, true],
    ['Следующий месяц, считая от самой недатированной заметки.', true, true, true],
    ['Следующий месяц отсчитывается от самой проверки; запись не датирована.', true, false, true],
    ['Следующий месяц отсчитывается от самой недатированной детали.', true, false, false],
    ['Следующий месяц отсчитывается от самой. Недатированная запись рядом.', true, false, true],
    ['В следующем месяце после исходной записи без известной календарной даты.', true, true, true],
    ['Завтра относительно заметки без известной даты.', true, true, true],
    ['Завтра относительно исходной записи с неизвестной календарной датой.', true, true, true],
    ['Завтра относительно заметки с неизвестной календарной датой', true, true, true],
    ['Завтра относительно записи с неизвестной календарной датой ремонта.', true, true, false],
    ['Завтра относительно записи с неизвестной датой ремонта.', true, true, false],
    ['Завтра относительно записи; встреча с неизвестной календарной датой.', true, true, false],
    ['Завтра относительно записи; устройство с неизвестной календарной датой.', true, true, false],
    [
      'В следующем месяце после исходной записи; устройство без известной календарной даты.',
      true,
      true,
      false,
    ],
    ['Завтра относительно заметки без известного датчика.', true, true, false],
    ['Завтра относительно заметки с известной календарной датой.', true, true, false],
    ['Next month refers to an undated source with an unknown calendar month.', true, true, true],
    [
      'Tomorrow refers to the moment of the undated source note; the corresponding calendar date cannot be recovered.',
      true,
      true,
      true,
    ],
    ['Next week; the calendar date is unknown because the source was undated.', true, true, true],
    ['Next week; the calendar date is unknown because the source had no date.', true, true, true],
    [
      'На следующей неделе; календарная дата неизвестна, поскольку исходная запись не датирована.',
      true,
      true,
      true,
    ],
    [
      'В следующем месяце, считая от недатированной заметки; месяц календарно определить нельзя.',
      true,
      true,
      true,
    ],
    [
      'В следующем месяце, отсчитывая его от недатированной записи; календарный месяц неизвестен.',
      true,
      true,
      true,
    ],
    ['В следующем месяце, считая от проверки устройства; календарный месяц неизвестен.', true, false, true],
    ['В следующем месяце, отсчитывая его от осмотра; дата неизвестна.', true, false, true],
    [
      'Следующая неделя после недатированной исходной записи; календарная неделя неизвестна.',
      true,
      true,
      true,
    ],
    ['На следующей неделе после недатированной заметки; календарная дата неизвестна.', true, true, true],
    ['В следующем месяце после исходной записи; дата записи отсутствует.', true, true, true],
    ['На следующей неделе после осмотра устройства; исходная запись не датирована.', true, false, true],
    ['На следующей неделе после передачи устройства; календарная дата неизвестна.', true, false, true],
    ['Завтра — относительно момента недатированной исходной заметки.', true, true, true],
    ['Завтра — это относительное время из недатированной записи.', true, true, true],
    ['Завтра было записано в источнике без даты; календарная дата неизвестна.', true, true, true],
    ['Next week is measured from the undated source note, whose date is unknown.', true, true, true],
    ['Tomorrow is counted from the original recording, with an unknown date.', true, true, true],
    ['Next month is reckoned from the moment of the source note, whose date is unknown.', true, true, true],
    [
      'Next week is understood from the moment of the source record; the record has no date.',
      true,
      true,
      true,
    ],
    ['Next month is understood from this undated note.', true, true, true],
    ['“Next month” is understood from this undated note.', true, true, true],
    ['`Next month` is understood from this undated note.', true, true, true],
    ["'Next month' is understood from this undated note.", true, true, true],
    ['‘Next month’ is understood from this undated note.', true, true, true],
    [
      "Example: 'Next month is understood from the source record.' The record has no date.",
      true,
      false,
      true,
    ],
    [
      'Example: ‘Next month is understood from the source record.’ The record has no date.',
      true,
      false,
      true,
    ],
    [
      'Example: `Next month is understood from the source record.` The record has no date.',
      true,
      false,
      true,
    ],
    ['Next month is not understood from the source record; the record has no date.', true, false, true],
    ['Next month is unknown. The cause was understood from the source record.', true, false, false],
    ['Next month is understood from the source record repair; the record has no date.', true, false, true],
    [
      'Example: “Next month is understood from the source record.” The record has no date.',
      true,
      false,
      true,
    ],
    ['Next month is understood from device pickup; the note has no date.', true, false, true],
    ['Next week is understood. From the source record, the device is described.', true, false, false],
    ['Next week is understood from the moment of processing; the note is undated.', true, false, true],
    ['Next week is measured from device pickup; the note is undated.', true, false, true],
    ['Next week is measured from the inspection, with an unknown date.', true, false, true],
    ['Next week relative to the undated original note.', true, true, true],
    ['The original note’s “next week,” with its reference date unknown.', true, true, true],
    ['Next week; the calendar date is unknown.', true, false, true],
    ['На следующей неделе; календарная дата неизвестна.', true, false, true],
    ['На следующей неделе относительно исходной недатированной записи.', true, true, true],
    ['Завтра относится к моменту той записи; дата неизвестна.', true, true, true],
    ['Next month relative to the original note; the device cannot be recovered.', true, true, false],
    ['An undated note discusses inspection.', false, false, true],
    ['Next week relative to the original note; the original note is undated.', true, true, true],
    ['Next week relative to the original note; the original note has no date.', true, true, true],
    ['Завтра относительно исходной записи; у исходной записи нет даты.', true, true, true],
    ['Завтра относительно исходной записи; дата исходной записи отсутствует.', true, true, true],
    ['Ada proposed the review; the date is unknown.', false, false, true],
    ['Ada proposed the review at a source-relative time whose date is unknown.', false, true, true],
    [
      'Tomorrow relative to the moment of the original record; its date cannot be recovered.',
      true,
      true,
      true,
    ],
    ['Tomorrow relative to the time of that undated note.', true, true, true],
    ['Tomorrow relative to the date of the original source; the calendar date is unknown.', true, true, true],
    ['Tomorrow relative to the moment of inspection; the calendar date is unknown.', true, false, true],
    ['Tomorrow relative to the time of device pickup; the note is undated.', true, false, true],
    ['Tomorrow relative to the moment of the source; the device cannot be recovered.', true, true, false],
    ['The device is undated.', false, false, false],
    ['The device has no date.', false, false, false],
  ] as const)(
    'keeps relative time, anchor and unknown clock separate: %s',
    (text, relative, anchor, unknown) => {
      expect(hasDeicticTime(text)).toBe(relative);
      expect(hasSourceRelativeAnchor(text)).toBe(anchor);
      expect(hasUnknownReferenceClock(text)).toBe(unknown);
    },
  );
});
